title: "Addison Ryne"
description: "Portfolio · CV · Research"
url: "https://AddisonRyne.github.io"

remote_theme: "mmistakes/so-simple-theme@3.2.0"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Top navigation links
nav:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/

author:
  name: "Addison Ryne"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:addisonryne01@gmail.com"
